name: Manual Make Workflow
on:
  workflow_dispatch: # Allows manual triggering of the workflow
jobs:
  build-and-push:
    runs-on: ubuntu-latest  
    permissions:       
      contents: write
      packages: write
    env: # Set environment variables globally for all steps
      DOCKER_PREFIX: ghcr.io/miskander/kubevirt
      DOCKER_TAG: ${{ github.sha }}
      PULLER_TIMEOUT: 2000
    steps:      
      - name: Checkout code
        uses: actions/checkout@v3     
      - name: docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u miskander --password-stdin   
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  
      - name: push
        run: docker pull alpine:latest && docker tag alpine:latest ghcr.io/miskander/kubevirt/virt-operator:foo && docker push ghcr.io/miskander/kubevirt/virt-operator:foo
      - name: make
        run: make             
      - name: make push
        run: make push             
      - name: make manifests
        run: make manifests        
