name: Manual Make Workflow

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env: # Set environment variables globally for all steps
      DOCKER_PREFIX: ghcr.io/miskander/kubevirt
      DOCKER_TAG: ${{ github.sha }}
      PULLER_TIMEOUT: 2000

    steps:      
      - name: Checkout code
        uses: actions/checkout@v3     
      - name: Run make
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u miskander --password-stdin   
      - name: Run make
        run: make             
      - name: Run make push
        run: make push             
      - name: Run make manifests
        run: make manifests        
